import type { GroundDecalPreset, ProjectilePreset, LaserPreset, StreamPreset, WavePreset } from "../kit/types";

/** Full elemental ground looks — pick a preset, mount GroundDecal. */
export const groundPresets = {
  earthSlam: {
    element: "earth",
    shape: "circle",
    colorCore: "#8b6914",
    colorMid: "#4a3423",
    colorEdge: "#1a100a",
    noiseScale: 6.8,
    breakup: 0.9,
    opacity: 1,
    radius: 2.35,
    lifeMs: 1800,
    ringWidth: 0.11,
    softness: 0.04,
    innerRatio: 0.15,
    spin: 0,
    appearEnd: 0.03,
    fadeStart: 0.78,
  },
  fireScorch: {
    element: "fire",
    shape: "circle",
    colorCore: "#fff7ed",
    colorMid: "#fb923c",
    colorEdge: "#7c2d12",
    noiseScale: 6.2,
    breakup: 0.8,
    opacity: 0.88,
    additive: true,
    radius: 2.1,
    lifeMs: 800,
    ringWidth: 0.1,
    softness: 0.08,
    spin: 0.4,
  },
  iceFrost: {
    element: "ice",
    shape: "ring",
    colorCore: "#e0f2fe",
    colorMid: "#7dd3fc",
    colorEdge: "#0c4a6e",
    noiseScale: 9.0,
    breakup: 0.55,
    opacity: 0.85,
    radius: 2.2,
    lifeMs: 900,
    ringWidth: 0.12,
    softness: 0.045,
    innerRatio: 0.42,
    spin: 0.15,
  },
  /** Slow shell that follows Frost Ball (held full opacity while mounted). */
  frostBallAura: {
    element: "ice",
    shape: "circle",
    colorCore: "#f0f9ff",
    colorMid: "#7dd3fc",
    colorEdge: "#075985",
    noiseScale: 8.5,
    breakup: 0.5,
    opacity: 0.7,
    radius: 4.5,
    lifeMs: 2000,
    ringWidth: 0.14,
    softness: 0.06,
    innerRatio: 0.15,
    /** Slow yaw for the following aura disc (rad/s). */
    spin: 0.45,
  },
  waterSplash: {
    element: "water",
    shape: "ring",
    colorCore: "#bae6fd",
    colorMid: "#38bdf8",
    colorEdge: "#075985",
    noiseScale: 5.5,
    breakup: 0.45,
    opacity: 0.7,
    radius: 2.0,
    lifeMs: 700,
    ringWidth: 0.14,
    softness: 0.1,
    innerRatio: 0.35,
    spin: 0,
  },
  windGust: {
    element: "wind",
    shape: "arc",
    colorCore: "#f8fafc",
    colorMid: "#cbd5e1",
    colorEdge: "#64748b",
    noiseScale: 8.5,
    breakup: 0.9,
    opacity: 0.65,
    radius: 2.4,
    lifeMs: 550,
    ringWidth: 0.16,
    softness: 0.09,
    arcSpan: Math.PI * 1.1,
    innerRatio: 0.5,
    spin: 1.8,
  },
  poisonBlot: {
    element: "poison",
    shape: "circle",
    colorCore: "#d8b4fe",
    colorMid: "#a78bfa",
    colorEdge: "#4a044e",
    noiseScale: 6.8,
    breakup: 0.78,
    opacity: 0.8,
    radius: 1.9,
    lifeMs: 950,
    ringWidth: 0.1,
    softness: 0.11,
    spin: 0.25,
  },
} as const satisfies Record<string, GroundDecalPreset>;

export type GroundPresetId = keyof typeof groundPresets;

/** Projectile look hooks — bolt migration later. */
export const projectilePresets = {
  fireOrb: {
    element: "fire",
    colorCore: "#fff7ed",
    colorMid: "#fb923c",
    colorEdge: "#9a3412",
    noiseScale: 4,
    breakup: 0.6,
    opacity: 0.9,
    additive: true,
    radius: 0.28,
    lifeMs: 400,
  },
  iceShard: {
    element: "ice",
    colorCore: "#e0f2fe",
    colorMid: "#38bdf8",
    colorEdge: "#0c4a6e",
    noiseScale: 5,
    breakup: 0.4,
    opacity: 0.85,
    radius: 0.22,
    lifeMs: 450,
  },
  poisonOrb: {
    element: "poison",
    colorCore: "#f5d0fe",
    colorMid: "#c084fc",
    colorEdge: "#581c87",
    noiseScale: 4.5,
    breakup: 0.7,
    opacity: 0.8,
    radius: 0.26,
    lifeMs: 480,
  },
  earthChunk: {
    element: "earth",
    colorCore: "#a8a29e",
    colorMid: "#78716c",
    colorEdge: "#292524",
    noiseScale: 3.5,
    breakup: 0.5,
    opacity: 0.9,
    radius: 0.3,
    lifeMs: 500,
  },
  waterOrb: {
    element: "water",
    colorCore: "#e0f2fe",
    colorMid: "#38bdf8",
    colorEdge: "#0369a1",
    noiseScale: 4,
    breakup: 0.45,
    opacity: 0.75,
    radius: 0.25,
    lifeMs: 420,
  },
  windOrb: {
    element: "wind",
    colorCore: "#f8fafc",
    colorMid: "#94a3b8",
    colorEdge: "#475569",
    noiseScale: 5,
    breakup: 0.85,
    opacity: 0.6,
    radius: 0.24,
    lifeMs: 380,
  },
} as const satisfies Record<string, ProjectilePreset>;

export const laserPresets = {
  fireBeam: {
    element: "fire",
    colorCore: "#fff7ed",
    colorMid: "#f97316",
    colorEdge: "#9a3412",
    noiseScale: 3,
    breakup: 0.5,
    opacity: 0.9,
    additive: true,
    width: 0.12,
    lifeMs: 280,
  },
  iceBeam: {
    element: "ice",
    colorCore: "#f0f9ff",
    colorMid: "#7dd3fc",
    colorEdge: "#0369a1",
    noiseScale: 3.5,
    breakup: 0.35,
    opacity: 0.85,
    width: 0.1,
    lifeMs: 300,
  },
  poisonBeam: {
    element: "poison",
    colorCore: "#faf5ff",
    colorMid: "#c084fc",
    colorEdge: "#6b21a8",
    noiseScale: 3.2,
    breakup: 0.55,
    opacity: 0.8,
    width: 0.11,
    lifeMs: 300,
  },
  waterBeam: {
    element: "water",
    colorCore: "#e0f2fe",
    colorMid: "#38bdf8",
    colorEdge: "#075985",
    noiseScale: 3,
    breakup: 0.4,
    opacity: 0.75,
    width: 0.11,
    lifeMs: 280,
  },
  windBeam: {
    element: "wind",
    colorCore: "#f8fafc",
    colorMid: "#cbd5e1",
    colorEdge: "#64748b",
    noiseScale: 4,
    breakup: 0.7,
    opacity: 0.65,
    width: 0.09,
    lifeMs: 240,
  },
  earthBeam: {
    element: "earth",
    colorCore: "#d6d3d1",
    colorMid: "#a8a29e",
    colorEdge: "#44403c",
    noiseScale: 2.8,
    breakup: 0.45,
    opacity: 0.85,
    width: 0.13,
    lifeMs: 300,
  },
} as const satisfies Record<string, LaserPreset>;

export const streamPresets = {
  fireBreath: {
    element: "fire",
    colorCore: "#fff7ed",
    colorMid: "#fb923c",
    colorEdge: "#9a3412",
    noiseScale: 4,
    breakup: 0.75,
    opacity: 0.85,
    additive: true,
    length: 4.5,
    halfAngle: 0.35,
    lifeMs: 600,
  },
  poisonSpray: {
    element: "poison",
    colorCore: "#f5d0fe",
    colorMid: "#a78bfa",
    colorEdge: "#581c87",
    noiseScale: 4.5,
    breakup: 0.8,
    opacity: 0.75,
    length: 4.0,
    halfAngle: 0.4,
    lifeMs: 650,
  },
  waterJet: {
    element: "water",
    colorCore: "#e0f2fe",
    colorMid: "#38bdf8",
    colorEdge: "#0369a1",
    noiseScale: 3.5,
    breakup: 0.5,
    opacity: 0.7,
    length: 4.2,
    halfAngle: 0.28,
    lifeMs: 550,
  },
  windBlast: {
    element: "wind",
    colorCore: "#f8fafc",
    colorMid: "#94a3b8",
    colorEdge: "#475569",
    noiseScale: 5,
    breakup: 0.9,
    opacity: 0.55,
    length: 5.0,
    halfAngle: 0.45,
    lifeMs: 480,
  },
  iceBreath: {
    element: "ice",
    colorCore: "#e0f2fe",
    colorMid: "#7dd3fc",
    colorEdge: "#0c4a6e",
    noiseScale: 4,
    breakup: 0.55,
    opacity: 0.8,
    length: 4.0,
    halfAngle: 0.32,
    lifeMs: 600,
  },
  earthSpray: {
    element: "earth",
    colorCore: "#a8a29e",
    colorMid: "#78716c",
    colorEdge: "#292524",
    noiseScale: 3.5,
    breakup: 0.65,
    opacity: 0.8,
    length: 3.5,
    halfAngle: 0.38,
    lifeMs: 580,
  },
} as const satisfies Record<string, StreamPreset>;

export const wavePresets = {
  earthShock: {
    element: "earth",
    colorCore: "#78716c",
    colorMid: "#57534e",
    colorEdge: "#1c1917",
    noiseScale: 6,
    breakup: 0.65,
    opacity: 0.85,
    radius: 3.2,
    ringWidth: 0.14,
    lifeMs: 700,
  },
  fireWave: {
    element: "fire",
    colorCore: "#fff7ed",
    colorMid: "#f97316",
    colorEdge: "#7c2d12",
    noiseScale: 5.5,
    breakup: 0.7,
    opacity: 0.8,
    additive: true,
    radius: 3.0,
    ringWidth: 0.12,
    lifeMs: 650,
  },
  iceWave: {
    element: "ice",
    colorCore: "#e0f2fe",
    colorMid: "#38bdf8",
    colorEdge: "#0c4a6e",
    noiseScale: 7,
    breakup: 0.5,
    opacity: 0.8,
    radius: 3.1,
    ringWidth: 0.11,
    lifeMs: 750,
  },
  waterWave: {
    element: "water",
    colorCore: "#bae6fd",
    colorMid: "#0ea5e9",
    colorEdge: "#075985",
    noiseScale: 5,
    breakup: 0.45,
    opacity: 0.7,
    radius: 3.4,
    ringWidth: 0.15,
    lifeMs: 800,
  },
  windWave: {
    element: "wind",
    colorCore: "#f8fafc",
    colorMid: "#cbd5e1",
    colorEdge: "#64748b",
    noiseScale: 8,
    breakup: 0.85,
    opacity: 0.6,
    radius: 3.6,
    ringWidth: 0.18,
    lifeMs: 550,
  },
  poisonWave: {
    element: "poison",
    colorCore: "#e9d5ff",
    colorMid: "#a78bfa",
    colorEdge: "#4c1d95",
    noiseScale: 6,
    breakup: 0.75,
    opacity: 0.75,
    radius: 2.9,
    ringWidth: 0.13,
    lifeMs: 780,
  },
} as const satisfies Record<string, WavePreset>;
