// AUTO-GENERATED by scripts/gen-map-index.mjs -- do not edit.
// Run `pnpm gen:maps` after adding or renaming a map document.

import { parseMapDoc } from "./mapDoc";
import { registerMapDoc } from "./registry";

import doc_arena_1 from "./arena_1.map.json";
import doc_arena_2 from "./arena_2.map.json";
import doc_pve_infinite_waves_1 from "./pve_infinite_waves_1.map.json";
import doc_village from "./village.map.json";

/**
 * A document that fails to parse is skipped rather than thrown: one bad map
 * should not stop the server booting or take the whole client down, and the
 * warning names the file to fix.
 */
function register(id: string, raw: unknown): void {
  const { doc, errors } = parseMapDoc(raw);
  if (!doc) {
    console.error(`[maps] "${id}" failed to parse and was skipped`, errors);
    return;
  }
  if (errors.length) console.warn(`[maps] "${id}" loaded with issues`, errors);
  registerMapDoc(doc);
}

/**
 * Registers every editor-authored map. Called once at startup by the server
 * and the client; safe to call twice, since registration is keyed by map id.
 */
export function registerAuthoredMaps(): void {
  register("arena_1", doc_arena_1);
  register("arena_2", doc_arena_2);
  register("pve_infinite_waves_1", doc_pve_infinite_waves_1);
  register("village", doc_village);
}

/** Ids of the authored maps compiled into this build. */
export const AUTHORED_MAP_IDS: readonly string[] = ["arena_1", "arena_2", "pve_infinite_waves_1", "village"];
