/**
 * Design-only talent catalog (100 entries from workbook).
 * Not equippable — promote into live TALENTS one-by-one.
 */
import type { SpellTag } from "./abilities";

export type TalentTreeId =
  | "Destruction"
  | "Guardian"
  | "Flow"
  | "Harmony"
  | "Control";

export type CatalogTalentDef = {
  id: string;
  tree: TalentTreeId;
  tier: number;
  requiredPoints: number;
  name: string;
  /**
   * Cost per rank invested.
   * Single-rank keystones use 2–3; multi-rank foundations use 1.
   */
  pointCost: number;
  /**
   * Max ranks. Omit to use defaults (tier-1 / cost-1 → 3, else 1).
   */
  maxRank?: number;
  affectedTags: readonly SpellTag[];
  exactEffect: string;
  balanceNote: string;
  status: "catalog";
  /**
   * Combat-ready. Omit / false = design-only (shown as "Not implemented" in the tree).
   * Flip to true when the talent is wired through resolveKit / live combat.
   */
  implemented?: boolean;
};

/** True only when explicitly marked combat-ready. */
export function isCatalogTalentImplemented(def: CatalogTalentDef | undefined): boolean {
  return def?.implemented === true;
}

export const TALENT_CATALOG: Record<string, CatalogTalentDef> = {
  "DES_01": {
    id: "DES_01",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Arcane Precision",
    pointCost: 1,
    affectedTags: ["Projectile"] as const,
    exactEffect: "Projectile speed +15%.",
    balanceNote: "Reliable projectile quality; no direct damage.",
    status: "catalog",
  },
  "DES_02": {
    id: "DES_02",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Demolition",
    pointCost: 1,
    affectedTags: ["Explosion"] as const,
    exactEffect: "Explosion radius +12%.",
    balanceNote: "Area coverage increase.",
    status: "catalog",
  },
  "DES_03": {
    id: "DES_03",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Pressure",
    pointCost: 1,
    affectedTags: ["Damage", "MultiHit"] as const,
    exactEffect: "Repeated hits on the same enemy within 4s grant +2% damage per stack, max 5.",
    balanceNote: "Maximum +10%; stacks are target-specific.",
    status: "catalog",
  },
  "DES_04": {
    id: "DES_04",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Quickened Impact",
    pointCost: 1,
    affectedTags: ["Damage", "Cast"] as const,
    exactEffect: "Damaging spells with a cast time complete 8% faster.",
    balanceNote: "Exclude channels and instant spells.",
    status: "catalog",
  },
  "DES_05": {
    id: "DES_05",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Scorching Wounds",
    pointCost: 1,
    affectedTags: ["DamageOverTime"] as const,
    exactEffect: "Damage-over-time effects reduce healing received by 8%.",
    balanceNote: "Does not stack with itself.",
    status: "catalog",
  },
  "DES_06": {
    id: "DES_06",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Focused Force",
    pointCost: 1,
    affectedTags: ["SingleTarget", "Damage"] as const,
    exactEffect: "Single-target spells deal +6% damage.",
    balanceNote: "Must not have Area, Nova, Chain, or Explosion.",
    status: "catalog",
  },
  "DES_07": {
    id: "DES_07",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Siege Magic",
    pointCost: 1,
    affectedTags: ["Barrier", "Summon", "Obstacle"] as const,
    exactEffect: "Deal +15% damage to barriers, summons, and obstacles.",
    balanceNote: "Utility damage only.",
    status: "catalog",
  },
  "DES_08": {
    id: "DES_08",
    tree: "Destruction",
    tier: 1,
    requiredPoints: 0,
    name: "Opening Salvo",
    pointCost: 1,
    affectedTags: ["Damage"] as const,
    exactEffect: "Your first damaging hit against an enemy deals +8% damage; 10s per-target cooldown.",
    balanceNote: "Encourages target switching.",
    status: "catalog",
  },
  "DES_09": {
    id: "DES_09",
    tree: "Destruction",
    tier: 2,
    requiredPoints: 4,
    name: "Heavy Projectiles",
    pointCost: 2,
    affectedTags: ["Projectile"] as const,
    exactEffect: "Projectile speed -20%, size +20%, damage +10%.",
    balanceNote: "Mutually exclusive with Needlecast.",
    status: "catalog",
  },
  "DES_10": {
    id: "DES_10",
    tree: "Destruction",
    tier: 2,
    requiredPoints: 4,
    name: "Needlecast",
    pointCost: 2,
    affectedTags: ["Projectile"] as const,
    exactEffect: "Projectile speed +30%, size -20%, damage +5%.",
    balanceNote: "Mutually exclusive with Heavy Projectiles.",
    status: "catalog",
  },
  "DES_11": {
    id: "DES_11",
    tree: "Destruction",
    tier: 2,
    requiredPoints: 4,
    name: "Piercing Force",
    pointCost: 2,
    affectedTags: ["Projectile"] as const,
    exactEffect: "Non-piercing projectiles pierce one enemy; existing pierce gains +1.",
    balanceNote: "Secondary hits deal 70% damage.",
    status: "catalog",
  },
  "DES_12": {
    id: "DES_12",
    tree: "Destruction",
    tier: 2,
    requiredPoints: 4,
    name: "Volatile Magic",
    pointCost: 2,
    affectedTags: ["Explosion"] as const,
    exactEffect: "Explosions apply a 15% slow for 1.25s.",
    balanceNote: "Control contribution kept modest.",
    status: "catalog",
  },
  "DES_13": {
    id: "DES_13",
    tree: "Destruction",
    tier: 2,
    requiredPoints: 4,
    name: "Chain Reaction",
    pointCost: 2,
    affectedTags: ["Explosion", "Area"] as const,
    exactEffect: "Hitting 2+ enemies refunds 8% of that spell's base cooldown.",
    balanceNote: "Once per cast.",
    status: "catalog",
  },
  "DES_14": {
    id: "DES_14",
    tree: "Destruction",
    tier: 2,
    requiredPoints: 4,
    name: "Accelerated Decay",
    pointCost: 2,
    affectedTags: ["DamageOverTime"] as const,
    exactEffect: "DoTs tick 20% faster and expire 16.7% sooner.",
    balanceNote: "Approximately unchanged total damage.",
    status: "catalog",
  },
  "DES_15": {
    id: "DES_15",
    tree: "Destruction",
    tier: 3,
    requiredPoints: 8,
    name: "Arcane Echo",
    pointCost: 2,
    affectedTags: ["Projectile"] as const,
    exactEffect: "Every fourth projectile cast creates a second projectile dealing 60% damage.",
    balanceNote: "Echo cannot trigger on echoes.",
    status: "catalog",
  },
  "DES_16": {
    id: "DES_16",
    tree: "Destruction",
    tier: 3,
    requiredPoints: 8,
    name: "Executioner",
    pointCost: 2,
    affectedTags: ["Damage"] as const,
    exactEffect: "Deal +10% damage to enemies below 25% health.",
    balanceNote: "Does not improve healing or shields.",
    status: "catalog",
  },
  "DES_17": {
    id: "DES_17",
    tree: "Destruction",
    tier: 3,
    requiredPoints: 8,
    name: "Overload",
    pointCost: 2,
    affectedTags: ["Damage", "Combo"] as const,
    exactEffect: "After casting 3 different damaging spell slots within 5s, gain 12% haste for 3s.",
    balanceNote: "8s internal cooldown.",
    status: "catalog",
  },
  "DES_18": {
    id: "DES_18",
    tree: "Destruction",
    tier: 3,
    requiredPoints: 8,
    name: "Rupture",
    pointCost: 2,
    affectedTags: ["Debuff", "Damage"] as const,
    exactEffect: "Damaging an enemy with 3 different mechanics applies Vulnerable: +7% damage taken for 3s.",
    balanceNote: "10s per-target cooldown.",
    status: "catalog",
  },
  "DES_19": {
    id: "DES_19",
    tree: "Destruction",
    tier: 4,
    requiredPoints: 12,
    name: "Glass Cannon",
    pointCost: 3,
    affectedTags: ["Damage"] as const,
    exactEffect: "Damage dealt +15%; maximum health -12%; healing received -8%.",
    balanceNote: "Keystone trade-off.",
    status: "catalog",
  },
  "DES_20": {
    id: "DES_20",
    tree: "Destruction",
    tier: 4,
    requiredPoints: 12,
    name: "Cataclysm",
    pointCost: 3,
    affectedTags: ["Explosion", "Area"] as const,
    exactEffect: "Every 18s, your next Explosion or Area damage spell gains +25% radius and +12% damage.",
    balanceNote: "Visible ready indicator required.",
    status: "catalog",
  },
  "GUA_01": {
    id: "GUA_01",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Thick Skin",
    pointCost: 1,
    affectedTags: ["DamageOverTime", "Defense"] as const,
    exactEffect: "Damage-over-time damage taken -15%.",
    balanceNote: "Narrow defensive counter.",
    status: "catalog",
  },
  "GUA_02": {
    id: "GUA_02",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Unshaken",
    pointCost: 1,
    affectedTags: ["Knockback", "Pull", "Knockup"] as const,
    exactEffect: "Displacement distance received -25%.",
    balanceNote: "Does not reduce stun duration.",
    status: "catalog",
  },
  "GUA_03": {
    id: "GUA_03",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Recovery",
    pointCost: 1,
    affectedTags: ["Healing", "Self"] as const,
    exactEffect: "After 5s without taking damage, regenerate 1.25% max health per second.",
    balanceNote: "Stops immediately on damage.",
    status: "catalog",
  },
  "GUA_04": {
    id: "GUA_04",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Brace",
    pointCost: 1,
    affectedTags: ["Cast", "Channel"] as const,
    exactEffect: "Take 8% less damage while casting or channeling.",
    balanceNote: "Not active during instant spells.",
    status: "catalog",
  },
  "GUA_05": {
    id: "GUA_05",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Lasting Guard",
    pointCost: 1,
    affectedTags: ["Shield"] as const,
    exactEffect: "Shields on you last 25% longer.",
    balanceNote: "Amount unchanged.",
    status: "catalog",
  },
  "GUA_06": {
    id: "GUA_06",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Steadfast",
    pointCost: 1,
    affectedTags: ["Defense"] as const,
    exactEffect: "While above 70% health, gain 5% damage reduction.",
    balanceNote: "Provides stable frontline value.",
    status: "catalog",
  },
  "GUA_07": {
    id: "GUA_07",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Emergency Step",
    pointCost: 1,
    affectedTags: ["Movement", "Defense"] as const,
    exactEffect: "Using a movement spell below 35% health grants a shield equal to 5% max health for 3s.",
    balanceNote: "15s cooldown.",
    status: "catalog",
  },
  "GUA_08": {
    id: "GUA_08",
    tree: "Guardian",
    tier: 1,
    requiredPoints: 0,
    name: "Protective Instinct",
    pointCost: 1,
    affectedTags: ["Defensive", "Ally"] as const,
    exactEffect: "Using a Defensive-slot spell grants the nearest ally 3% damage reduction for 2s.",
    balanceNote: "6s cooldown.",
    status: "catalog",
  },
  "GUA_09": {
    id: "GUA_09",
    tree: "Guardian",
    tier: 2,
    requiredPoints: 4,
    name: "Reinforced Barrier",
    pointCost: 2,
    affectedTags: ["Shield"] as const,
    exactEffect: "Shield strength +14%.",
    balanceNote: "Applies to self and ally shields.",
    status: "catalog",
  },
  "GUA_10": {
    id: "GUA_10",
    tree: "Guardian",
    tier: 2,
    requiredPoints: 4,
    name: "Iron Will",
    pointCost: 2,
    affectedTags: ["Stun", "Root", "Silence", "Fear"] as const,
    exactEffect: "The first hard CC received every 18s has 35% shorter duration.",
    balanceNote: "Hard CC list should be explicit.",
    status: "catalog",
  },
  "GUA_11": {
    id: "GUA_11",
    tree: "Guardian",
    tier: 2,
    requiredPoints: 4,
    name: "Reflective Shield",
    pointCost: 2,
    affectedTags: ["Shield", "Damage"] as const,
    exactEffect: "When one of your shields is fully destroyed, deal damage equal to 20% of its original value in 3m.",
    balanceNote: "12s cooldown.",
    status: "catalog",
  },
  "GUA_12": {
    id: "GUA_12",
    tree: "Guardian",
    tier: 2,
    requiredPoints: 4,
    name: "Delayed Pain",
    pointCost: 2,
    affectedTags: ["Defense"] as const,
    exactEffect: "20% of direct damage taken is delayed over 3s.",
    balanceNote: "Delayed portion cannot be delayed again.",
    status: "catalog",
  },
  "GUA_13": {
    id: "GUA_13",
    tree: "Guardian",
    tier: 2,
    requiredPoints: 4,
    name: "Counterguard",
    pointCost: 2,
    affectedTags: ["Defense", "Damage"] as const,
    exactEffect: "After blocking, absorbing, or becoming immune to damage, your next damaging spell within 4s deals +8%.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "GUA_14": {
    id: "GUA_14",
    tree: "Guardian",
    tier: 2,
    requiredPoints: 4,
    name: "Grounded",
    pointCost: 2,
    affectedTags: ["GroundEffect", "Defense"] as const,
    exactEffect: "While inside one of your persistent areas, take 7% less damage.",
    balanceNote: "One instance only.",
    status: "catalog",
  },
  "GUA_15": {
    id: "GUA_15",
    tree: "Guardian",
    tier: 3,
    requiredPoints: 8,
    name: "Last Stand",
    pointCost: 2,
    affectedTags: ["Defense"] as const,
    exactEffect: "Below 30% health, gain 12% damage reduction until above 45%.",
    balanceNote: "20s cooldown after ending.",
    status: "catalog",
  },
  "GUA_16": {
    id: "GUA_16",
    tree: "Guardian",
    tier: 3,
    requiredPoints: 8,
    name: "Battle Hardened",
    pointCost: 2,
    affectedTags: ["Defense", "Cooldown"] as const,
    exactEffect: "Taking damage equal to 20% max health within 3s reduces Defensive-slot cooldown by 12%.",
    balanceNote: "10s cooldown.",
    status: "catalog",
  },
  "GUA_17": {
    id: "GUA_17",
    tree: "Guardian",
    tier: 3,
    requiredPoints: 8,
    name: "Shared Bulwark",
    pointCost: 2,
    affectedTags: ["Shield", "Ally"] as const,
    exactEffect: "15% of shields you grant yourself are also granted to the nearest ally.",
    balanceNote: "Ally shield lasts max 4s.",
    status: "catalog",
  },
  "GUA_18": {
    id: "GUA_18",
    tree: "Guardian",
    tier: 3,
    requiredPoints: 8,
    name: "Guardian's Challenge",
    pointCost: 2,
    affectedTags: ["Debuff", "Ally"] as const,
    exactEffect: "Damaging an enemy marks them for 4s; they deal 6% less damage to your allies.",
    balanceNote: "No reduction against you; 8s per target.",
    status: "catalog",
  },
  "GUA_19": {
    id: "GUA_19",
    tree: "Guardian",
    tier: 4,
    requiredPoints: 12,
    name: "Living Fortress",
    pointCost: 3,
    affectedTags: ["Defense"] as const,
    exactEffect: "After standing still for 1.5s: +12% damage reduction, +20% displacement resistance, +10% shield power. Ends on movement.",
    balanceNote: "Keystone; clear stance feedback.",
    status: "catalog",
  },
  "GUA_20": {
    id: "GUA_20",
    tree: "Guardian",
    tier: 4,
    requiredPoints: 12,
    name: "Unbreakable",
    pointCost: 3,
    affectedTags: ["Defense"] as const,
    exactEffect: "Lethal damage instead leaves you at 1 health and grants 20% max-health shield for 2s.",
    balanceNote: "90s cooldown.",
    status: "catalog",
  },
  "CON_01": {
    id: "CON_01",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Lasting Effects",
    pointCost: 1,
    affectedTags: ["Slow"] as const,
    exactEffect: "Slow duration +20%.",
    balanceNote: "Does not increase strength.",
    status: "catalog",
  },
  "CON_02": {
    id: "CON_02",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Tactical Vision",
    pointCost: 1,
    affectedTags: ["CrowdControl", "Reveal"] as const,
    exactEffect: "Enemies you control remain revealed for 2s after the effect ends.",
    balanceNote: "Useful against stealth and fog.",
    status: "catalog",
  },
  "CON_03": {
    id: "CON_03",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Opportunist",
    pointCost: 1,
    affectedTags: ["CrowdControl", "Damage"] as const,
    exactEffect: "Deal +6% damage to enemies currently affected by your CC.",
    balanceNote: "Does not apply to simple debuffs.",
    status: "catalog",
  },
  "CON_04": {
    id: "CON_04",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Sticky Ground",
    pointCost: 1,
    affectedTags: ["GroundEffect", "Persistent"] as const,
    exactEffect: "Non-damaging ground effects last 15% longer.",
    balanceNote: "Damage duration unchanged.",
    status: "catalog",
  },
  "CON_05": {
    id: "CON_05",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Suppressive Magic",
    pointCost: 1,
    affectedTags: ["Debuff"] as const,
    exactEffect: "Debuffs you apply last 12% longer.",
    balanceNote: "Excludes hard CC.",
    status: "catalog",
  },
  "CON_06": {
    id: "CON_06",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Spatial Control",
    pointCost: 1,
    affectedTags: ["Wall", "Obstacle"] as const,
    exactEffect: "Walls and obstacles last 15% longer and gain 12% health.",
    balanceNote: "Map clutter cap required.",
    status: "catalog",
  },
  "CON_07": {
    id: "CON_07",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Crippling Chill",
    pointCost: 1,
    affectedTags: ["Slow", "Movement"] as const,
    exactEffect: "Slowed enemies receive 10% less movement from movement-speed bonuses.",
    balanceNote: "Does not disable movement spells.",
    status: "catalog",
  },
  "CON_08": {
    id: "CON_08",
    tree: "Control",
    tier: 1,
    requiredPoints: 0,
    name: "Watchful",
    pointCost: 1,
    affectedTags: ["Interrupt"] as const,
    exactEffect: "Successful interrupts reveal the target and their cooldown indicators for 3s.",
    balanceNote: "Information talent.",
    status: "catalog",
  },
  "CON_09": {
    id: "CON_09",
    tree: "Control",
    tier: 2,
    requiredPoints: 4,
    name: "Frozen Momentum",
    pointCost: 2,
    affectedTags: ["Root", "Slow"] as const,
    exactEffect: "When your root ends, apply a 25% slow for 1.5s.",
    balanceNote: "Does not trigger when cleansed.",
    status: "catalog",
  },
  "CON_10": {
    id: "CON_10",
    tree: "Control",
    tier: 2,
    requiredPoints: 4,
    name: "Crushing Force",
    pointCost: 2,
    affectedTags: ["Knockback", "Knockup"] as const,
    exactEffect: "Displacement applies a 20% slow for 1.25s.",
    balanceNote: "Once per cast.",
    status: "catalog",
  },
  "CON_11": {
    id: "CON_11",
    tree: "Control",
    tier: 2,
    requiredPoints: 4,
    name: "Unstable Ground",
    pointCost: 2,
    affectedTags: ["Area", "GroundEffect"] as const,
    exactEffect: "Area control spells leave a 2s zone that slows by 15%.",
    balanceNote: "6s per-spell cooldown.",
    status: "catalog",
  },
  "CON_12": {
    id: "CON_12",
    tree: "Control",
    tier: 2,
    requiredPoints: 4,
    name: "Silencing Pressure",
    pointCost: 2,
    affectedTags: ["Interrupt", "Silence"] as const,
    exactEffect: "Interrupting a spell silences the target for 0.5s.",
    balanceNote: "12s per-target cooldown.",
    status: "catalog",
  },
  "CON_13": {
    id: "CON_13",
    tree: "Control",
    tier: 2,
    requiredPoints: 4,
    name: "No Escape",
    pointCost: 2,
    affectedTags: ["CrowdControl", "Movement"] as const,
    exactEffect: "Enemies using a movement spell while affected by your slow or debuff are slowed by 30% for 1s afterward.",
    balanceNote: "8s per target.",
    status: "catalog",
  },
  "CON_14": {
    id: "CON_14",
    tree: "Control",
    tier: 2,
    requiredPoints: 4,
    name: "Control Chain",
    pointCost: 2,
    affectedTags: ["CrowdControl", "Combo"] as const,
    exactEffect: "Applying a different CC category within 3s increases the second effect's duration by 12%.",
    balanceNote: "Hard cap +0.3s.",
    status: "catalog",
  },
  "CON_15": {
    id: "CON_15",
    tree: "Control",
    tier: 3,
    requiredPoints: 8,
    name: "Tactical Reset",
    pointCost: 2,
    affectedTags: ["CrowdControl", "Movement"] as const,
    exactEffect: "Controlling two different enemies within 4s reduces Movement-slot cooldown by 15%.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "CON_16": {
    id: "CON_16",
    tree: "Control",
    tier: 3,
    requiredPoints: 8,
    name: "Interrupt Master",
    pointCost: 2,
    affectedTags: ["Interrupt", "Resource"] as const,
    exactEffect: "Successful interrupts restore 10% maximum resource.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "CON_17": {
    id: "CON_17",
    tree: "Control",
    tier: 3,
    requiredPoints: 8,
    name: "Zone Mastery",
    pointCost: 2,
    affectedTags: ["Area", "Persistent"] as const,
    exactEffect: "Persistent control areas gain +12% radius but deal 8% less damage.",
    balanceNote: "Trade-off.",
    status: "catalog",
  },
  "CON_18": {
    id: "CON_18",
    tree: "Control",
    tier: 3,
    requiredPoints: 8,
    name: "Diminishing Pressure",
    pointCost: 2,
    affectedTags: ["Debuff"] as const,
    exactEffect: "Enemies affected by 2+ of your debuffs deal 7% less damage to you.",
    balanceNote: "Personal protection only.",
    status: "catalog",
  },
  "CON_19": {
    id: "CON_19",
    tree: "Control",
    tier: 4,
    requiredPoints: 12,
    name: "Domination",
    pointCost: 3,
    affectedTags: ["CrowdControl", "Combo"] as const,
    exactEffect: "Applying 3 different CC categories within 8s creates a 3.5m field for 3s: enemies are slowed 25% and deal 8% less damage.",
    balanceNote: "18s cooldown.",
    status: "catalog",
  },
  "CON_20": {
    id: "CON_20",
    tree: "Control",
    tier: 4,
    requiredPoints: 12,
    name: "Time Lock",
    pointCost: 3,
    affectedTags: ["Cooldown", "Debuff"] as const,
    exactEffect: "Every 20s, your next hard CC pauses 25% of the target's current basic cooldown recovery for 2s.",
    balanceNote: "Does not affect ultimate cooldown.",
    status: "catalog",
  },
  "FLO_01": {
    id: "FLO_01",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Momentum",
    pointCost: 1,
    affectedTags: ["Movement"] as const,
    exactEffect: "After using a Movement-slot spell, gain 10% movement speed for 2s.",
    balanceNote: "Does not stack.",
    status: "catalog",
  },
  "FLO_02": {
    id: "FLO_02",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Spell Rhythm",
    pointCost: 1,
    affectedTags: ["Combo", "SpellSlot"] as const,
    exactEffect: "Casting 3 different spell slots within 5s grants 8% movement speed for 3s.",
    balanceNote: "6s cooldown.",
    status: "catalog",
  },
  "FLO_03": {
    id: "FLO_03",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Resource Cycle",
    pointCost: 1,
    affectedTags: ["Movement", "Resource"] as const,
    exactEffect: "Movement-slot spells restore 6% maximum resource.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "FLO_04": {
    id: "FLO_04",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Fluid Casting",
    pointCost: 1,
    affectedTags: ["Cast", "Movement"] as const,
    exactEffect: "Moving during a cast reduces the movement penalty by 25%.",
    balanceNote: "Only spells permitting movement.",
    status: "catalog",
  },
  "FLO_05": {
    id: "FLO_05",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Quick Recovery",
    pointCost: 1,
    affectedTags: ["Cooldown"] as const,
    exactEffect: "Missing an aimed spell refunds 5% of its base cooldown.",
    balanceNote: "Does not apply to ultimate; once per cast.",
    status: "catalog",
  },
  "FLO_06": {
    id: "FLO_06",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Close the Gap",
    pointCost: 1,
    affectedTags: ["Damage", "Movement"] as const,
    exactEffect: "Damaging an enemy over 8m away grants 8% movement speed toward them for 2s.",
    balanceNote: "4s cooldown.",
    status: "catalog",
  },
  "FLO_07": {
    id: "FLO_07",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Evasive Casting",
    pointCost: 1,
    affectedTags: ["Movement", "Defense"] as const,
    exactEffect: "For 1s after a movement spell, take 6% less damage.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "FLO_08": {
    id: "FLO_08",
    tree: "Flow",
    tier: 1,
    requiredPoints: 0,
    name: "Efficient Sequence",
    pointCost: 1,
    affectedTags: ["Combo", "Resource"] as const,
    exactEffect: "Casting two different spell slots consecutively reduces the second spell's resource cost by 8%.",
    balanceNote: "Repeating a slot resets sequence.",
    status: "catalog",
  },
  "FLO_09": {
    id: "FLO_09",
    tree: "Flow",
    tier: 2,
    requiredPoints: 4,
    name: "Afterimage",
    pointCost: 2,
    affectedTags: ["Movement", "Explosion"] as const,
    exactEffect: "Movement spells leave an afterimage that explodes after 0.65s for 45 base damage in 2.25m.",
    balanceNote: "8s cooldown; scale with standard power.",
    status: "catalog",
  },
  "FLO_10": {
    id: "FLO_10",
    tree: "Flow",
    tier: 2,
    requiredPoints: 4,
    name: "Combo Engine",
    pointCost: 2,
    affectedTags: ["Combo", "Cooldown"] as const,
    exactEffect: "Casting Movement → Primary → Secondary within 5s reduces remaining non-ultimate cooldowns by 7%.",
    balanceNote: "10s cooldown.",
    status: "catalog",
  },
  "FLO_11": {
    id: "FLO_11",
    tree: "Flow",
    tier: 2,
    requiredPoints: 4,
    name: "Chaser",
    pointCost: 2,
    affectedTags: ["Damage", "Movement"] as const,
    exactEffect: "Gain 12% movement speed while moving toward an enemy you damaged in the last 2s.",
    balanceNote: "Ends when facing away.",
    status: "catalog",
  },
  "FLO_12": {
    id: "FLO_12",
    tree: "Flow",
    tier: 2,
    requiredPoints: 4,
    name: "Slipstream",
    pointCost: 2,
    affectedTags: ["Movement", "Ally"] as const,
    exactEffect: "Passing within 2m of an ally after a movement spell grants both 8% movement speed for 2s.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "FLO_13": {
    id: "FLO_13",
    tree: "Flow",
    tier: 2,
    requiredPoints: 4,
    name: "Adaptive Casting",
    pointCost: 2,
    affectedTags: ["SpellSlot", "Cooldown"] as const,
    exactEffect: "After casting a spell slot, the next different slot gains 8% cooldown recovery for 3s.",
    balanceNote: "One spell consumed.",
    status: "catalog",
  },
  "FLO_14": {
    id: "FLO_14",
    tree: "Flow",
    tier: 2,
    requiredPoints: 4,
    name: "Overflowing Energy",
    pointCost: 2,
    affectedTags: ["Resource", "Shield"] as const,
    exactEffect: "Resource gained above maximum becomes a shield at 50% efficiency, capped at 6% max health.",
    balanceNote: "Shield lasts 4s.",
    status: "catalog",
  },
  "FLO_15": {
    id: "FLO_15",
    tree: "Flow",
    tier: 3,
    requiredPoints: 8,
    name: "Adrenaline",
    pointCost: 2,
    affectedTags: ["Combo", "Haste"] as const,
    exactEffect: "Casting 4 spells within 6s grants 12% haste for 3s.",
    balanceNote: "12s cooldown.",
    status: "catalog",
  },
  "FLO_16": {
    id: "FLO_16",
    tree: "Flow",
    tier: 3,
    requiredPoints: 8,
    name: "Phase Step",
    pointCost: 2,
    affectedTags: ["Movement", "Cleanse"] as const,
    exactEffect: "Movement-slot spells remove slows and grant slow immunity for 0.75s.",
    balanceNote: "14s cooldown.",
    status: "catalog",
  },
  "FLO_17": {
    id: "FLO_17",
    tree: "Flow",
    tier: 3,
    requiredPoints: 8,
    name: "Tempo Shift",
    pointCost: 2,
    affectedTags: ["Cooldown", "Combo"] as const,
    exactEffect: "Casting a spell with 8s+ base cooldown reduces the next spell below 8s by 10%.",
    balanceNote: "6s cooldown.",
    status: "catalog",
  },
  "FLO_18": {
    id: "FLO_18",
    tree: "Flow",
    tier: 3,
    requiredPoints: 8,
    name: "Arcane Momentum",
    pointCost: 2,
    affectedTags: ["SpellSlot", "Combo"] as const,
    exactEffect: "Casting without repeating a spell slot grants 1 Momentum; at 4, restore 8% resource and reduce cooldowns by 5%.",
    balanceNote: "Repeating resets stacks.",
    status: "catalog",
  },
  "FLO_19": {
    id: "FLO_19",
    tree: "Flow",
    tier: 4,
    requiredPoints: 12,
    name: "Perfect Flow",
    pointCost: 3,
    affectedTags: ["SpellSlot", "Haste"] as const,
    exactEffect: "Each different spell slot cast grants 2% haste for 5s, max 5 stacks. Repeating a slot removes all stacks.",
    balanceNote: "Keystone.",
    status: "catalog",
  },
  "FLO_20": {
    id: "FLO_20",
    tree: "Flow",
    tier: 4,
    requiredPoints: 12,
    name: "Untouchable Rhythm",
    pointCost: 3,
    affectedTags: ["Movement", "Defense"] as const,
    exactEffect: "After casting 3 different slots within 4s, become untargetable by homing effects and gain 15% movement speed for 1.5s.",
    balanceNote: "15s cooldown.",
    status: "catalog",
  },
  "HAR_01": {
    id: "HAR_01",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Overflow",
    pointCost: 1,
    affectedTags: ["Healing", "Shield"] as const,
    exactEffect: "40% of overhealing becomes a shield lasting 5s, capped at 8% target max health.",
    balanceNote: "Does not trigger from self-regeneration.",
    status: "catalog",
  },
  "HAR_02": {
    id: "HAR_02",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Encouragement",
    pointCost: 1,
    affectedTags: ["Healing", "Ally"] as const,
    exactEffect: "Healing an ally grants them 10% movement speed for 2s.",
    balanceNote: "6s per target.",
    status: "catalog",
  },
  "HAR_03": {
    id: "HAR_03",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Shared Strength",
    pointCost: 1,
    affectedTags: ["Shield", "Ally"] as const,
    exactEffect: "Granting an ally a shield also shields you for 15% of that amount.",
    balanceNote: "4s cooldown.",
    status: "catalog",
  },
  "HAR_04": {
    id: "HAR_04",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Spiritual Focus",
    pointCost: 1,
    affectedTags: ["Healing", "Resource"] as const,
    exactEffect: "Healing an ally restores 3% maximum resource.",
    balanceNote: "6s cooldown.",
    status: "catalog",
  },
  "HAR_05": {
    id: "HAR_05",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Lingering Care",
    pointCost: 1,
    affectedTags: ["HealOverTime", "Buff"] as const,
    exactEffect: "Heal-over-time and beneficial buff durations +15%.",
    balanceNote: "Total HoT healing rises accordingly.",
    status: "catalog",
  },
  "HAR_06": {
    id: "HAR_06",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Gentle Current",
    pointCost: 1,
    affectedTags: ["Healing", "Projectile"] as const,
    exactEffect: "Healing projectiles gain +20% speed and +10% size.",
    balanceNote: "No healing amount increase.",
    status: "catalog",
  },
  "HAR_07": {
    id: "HAR_07",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Mutual Aid",
    pointCost: 1,
    affectedTags: ["Ally", "Healing"] as const,
    exactEffect: "When an ally heals or shields you, your next support spell within 4s is 6% stronger.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "HAR_08": {
    id: "HAR_08",
    tree: "Harmony",
    tier: 1,
    requiredPoints: 0,
    name: "Battlefield Medic",
    pointCost: 1,
    affectedTags: ["Healing"] as const,
    exactEffect: "Healing allies who took damage in the last 2s is increased by 6%.",
    balanceNote: "Does not affect self-healing.",
    status: "catalog",
  },
  "HAR_09": {
    id: "HAR_09",
    tree: "Harmony",
    tier: 2,
    requiredPoints: 4,
    name: "Guardian Angel",
    pointCost: 2,
    affectedTags: ["Healing", "Ally"] as const,
    exactEffect: "Healing allies below 30% health is increased by 18%.",
    balanceNote: "Emergency specialization.",
    status: "catalog",
  },
  "HAR_10": {
    id: "HAR_10",
    tree: "Harmony",
    tier: 2,
    requiredPoints: 4,
    name: "Purification",
    pointCost: 2,
    affectedTags: ["Cleanse", "Buff"] as const,
    exactEffect: "Cleansing an ally grants 20% slow resistance and 10% movement speed for 2s.",
    balanceNote: "10s per target.",
    status: "catalog",
  },
  "HAR_11": {
    id: "HAR_11",
    tree: "Harmony",
    tier: 2,
    requiredPoints: 4,
    name: "Resonance",
    pointCost: 2,
    affectedTags: ["Healing", "Combo"] as const,
    exactEffect: "Healing two different allies within 4s empowers your next heal by 12%.",
    balanceNote: "6s cooldown after consumption.",
    status: "catalog",
  },
  "HAR_12": {
    id: "HAR_12",
    tree: "Harmony",
    tier: 2,
    requiredPoints: 4,
    name: "Protective Bloom",
    pointCost: 2,
    affectedTags: ["Shield", "Area"] as const,
    exactEffect: "When an ally shield expires naturally, nearby allies receive 12% of its original amount.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "HAR_13": {
    id: "HAR_13",
    tree: "Harmony",
    tier: 2,
    requiredPoints: 4,
    name: "Inspiration",
    pointCost: 2,
    affectedTags: ["Buff", "Cooldown"] as const,
    exactEffect: "Applying a beneficial buff to an ally reduces your longest non-ultimate cooldown by 5%.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "HAR_14": {
    id: "HAR_14",
    tree: "Harmony",
    tier: 2,
    requiredPoints: 4,
    name: "Life Link",
    pointCost: 2,
    affectedTags: ["Healing", "Ally"] as const,
    exactEffect: "20% of self-healing also heals the lowest-health ally within 8m.",
    balanceNote: "Excludes regeneration talents.",
    status: "catalog",
  },
  "HAR_15": {
    id: "HAR_15",
    tree: "Harmony",
    tier: 3,
    requiredPoints: 8,
    name: "Shared Recovery",
    pointCost: 2,
    affectedTags: ["Healing", "Area"] as const,
    exactEffect: "Directly healing yourself emits a heal equal to 15% of the amount to allies within 4m.",
    balanceNote: "8s cooldown.",
    status: "catalog",
  },
  "HAR_16": {
    id: "HAR_16",
    tree: "Harmony",
    tier: 3,
    requiredPoints: 8,
    name: "Bolstering Aid",
    pointCost: 2,
    affectedTags: ["Healing", "Buff"] as const,
    exactEffect: "Healing an ally grants them 5% damage reduction for 2s.",
    balanceNote: "8s per target.",
    status: "catalog",
  },
  "HAR_17": {
    id: "HAR_17",
    tree: "Harmony",
    tier: 3,
    requiredPoints: 8,
    name: "Clean Momentum",
    pointCost: 2,
    affectedTags: ["Cleanse", "Cooldown"] as const,
    exactEffect: "Successful cleanse reduces Movement-slot cooldown by 15%.",
    balanceNote: "10s cooldown.",
    status: "catalog",
  },
  "HAR_18": {
    id: "HAR_18",
    tree: "Harmony",
    tier: 3,
    requiredPoints: 8,
    name: "Empowered Support",
    pointCost: 2,
    affectedTags: ["Healing", "Shield"] as const,
    exactEffect: "After dealing damage with 2 different spell slots, your next heal or shield is 15% stronger.",
    balanceNote: "8s duration.",
    status: "catalog",
  },
  "HAR_19": {
    id: "HAR_19",
    tree: "Harmony",
    tier: 4,
    requiredPoints: 12,
    name: "Divine Resonance",
    pointCost: 3,
    affectedTags: ["Healing", "Shield"] as const,
    exactEffect: "Heals and shields grant Resonance, max 5. At 5, next support spell is 30% stronger, costs no resource, and gains 15% range.",
    balanceNote: "Keystone; one stack per cast.",
    status: "catalog",
  },
  "HAR_20": {
    id: "HAR_20",
    tree: "Harmony",
    tier: 4,
    requiredPoints: 12,
    name: "Circle of Life",
    pointCost: 3,
    affectedTags: ["Healing", "Damage"] as const,
    exactEffect: "Every 18s, dealing damage stores 20% of damage dealt, capped at 10% max health; your next ally heal adds the stored amount.",
    balanceNote: "Keystone hybrid support.",
    status: "catalog",
  },
};

export const TALENT_CATALOG_IDS = Object.keys(TALENT_CATALOG);
