import { ATLAS_UV } from "./atlas";
import { spawnEmitter, setEmitterPose, setEmitterRate, killEmitter } from "./director";
import { BatchId, Collide, LodRank, type EmitterSpawn } from "./types";
import type { ElementId } from "./elementGallery";

/**
 * Per-element emitter recipes split by the role they play in a spell beat.
 *
 * The gallery in `elementGallery.ts` proves an element reads as itself standing still;
 * these are the same layering method (Ardent Wilds core + sparks + mist) retuned for
 * the four places a spell actually needs particles. Spell files compose roles instead
 * of hand-authoring emitter configs, so an element stays consistent across abilities
 * and a retune lands everywhere at once.
 */
export type ElementRole =
  /** Caster tell at the hand — tight, bright, short-lived. */
  | "cast"
  /** Projectile / stream wake — cheap, trail-ranked, no mist. */
  | "trail"
  /** Landing on a body — the loud beat, bursts on spawn. */
  | "impact"
  /** Lingering surface at y≈0 — zone identity, must survive seconds. */
  | "ground";

/** Layer recipe: everything except where it lives in the world. */
type Layer = Omit<EmitterSpawn, "x" | "y" | "z">;

const FIRE_HOT = "#fffbeb";
const FIRE_MID = "#fb923c";
const FIRE_DEEP = "#ea580c";
const EMBER_HOT = "#fef08a";
const EMBER_MID = "#f97316";
const EMBER_DEEP = "#b91c1c";
const SMOKE_HOT = "#6b503f";
const SMOKE_MID = "#3b2c25";
const SMOKE_DEEP = "#141010";

const ICE_HOT = "#ffffff";
const ICE_MID = "#bae6fd";
const ICE_DEEP = "#38bdf8";
const FROST_FOG_HOT = "#f2feff";
const FROST_FOG_MID = "#cdefff";
const FROST_FOG_DEEP = "#09304c";

const TOX_HOT = "#ecfccb";
const TOX_MID = "#84cc16";
const TOX_DEEP = "#3f6212";
const TOX_FOG_HOT = "#a3e635";
const TOX_FOG_MID = "#4d7c0f";
const TOX_FOG_DEEP = "#1a2e05";

const ARC_HOT = "#ffffff";
const ARC_MID = "#e0f2fe";
const ARC_DEEP = "#38bdf8";

const VOID_HOT = "#f5d0fe";
const VOID_MID = "#c026d3";
const VOID_DEEP = "#6b21a8";
const VOID_MASS_HOT = "#1e0736";
const VOID_MASS_MID = "#2e1065";
const VOID_MASS_DEEP = "#0c0218";

const WIND_HOT = "#f8fafc";
const WIND_MID = "#e2e8f0";
const WIND_DEEP = "#94a3b8";

const LEAF_HOT = "#ecfccb";
const LEAF_MID = "#86efac";
const LEAF_DEEP = "#16a34a";

const HOLY_HOT = "#fffbeb";
const HOLY_MID = "#fef08a";
const HOLY_DEEP = "#eab308";

const BLOOD_HOT = "#fecaca";
const BLOOD_MID = "#ef4444";
const BLOOD_DEEP = "#7f1d1d";

/** Shared base — every preset lives in world space and ignores collision. */
const BASE: Layer = {
  groundY: 0,
  collide: Collide.None,
};

const PRESETS: Record<ElementId, Record<ElementRole, readonly Layer[]>> = {
  fire: {
    cast: [
      {
        batch: BatchId.AdditiveFire,
        atlasUv: ATLAS_UV.fire,
        rate: 54,
        dirY: 1.5,
        spread: 0.34,
        gravity: -0.35,
        drag: 0.6,
        noise: 0.5,
        size: 0.42,
        sizeEnd: 0.1,
        life: 0.4,
        lifeJitter: 0.25,
        burst: 8,
        rotRate: 1.4,
        color0: FIRE_HOT,
        color1: FIRE_MID,
        color2: FIRE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 26,
        dirY: 1.1,
        spread: 0.5,
        gravity: 0.7,
        drag: 0.3,
        noise: 0.6,
        size: 0.13,
        sizeEnd: 0.025,
        life: 0.52,
        lifeJitter: 0.35,
        burst: 5,
        color0: EMBER_HOT,
        color1: EMBER_MID,
        color2: EMBER_DEEP,
        lod: LodRank.Trail,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveFire,
        atlasUv: ATLAS_UV.fire,
        rate: 46,
        dirY: 0.5,
        spread: 0.3,
        gravity: -0.5,
        drag: 0.9,
        noise: 0.45,
        size: 0.4,
        sizeEnd: 0.08,
        life: 0.34,
        lifeJitter: 0.3,
        rotRate: 1.6,
        color0: FIRE_HOT,
        color1: FIRE_MID,
        color2: FIRE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 24,
        dirY: 0.3,
        spread: 0.55,
        gravity: 1.5,
        drag: 0.2,
        noise: 0.7,
        size: 0.1,
        sizeEnd: 0.02,
        life: 0.55,
        lifeJitter: 0.4,
        color0: EMBER_HOT,
        color1: EMBER_MID,
        color2: EMBER_DEEP,
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        batch: BatchId.AdditiveFire,
        atlasUv: ATLAS_UV.fire,
        rate: 0,
        dirY: 2.2,
        spread: 0.85,
        gravity: -0.8,
        drag: 1.1,
        noise: 0.6,
        size: 0.85,
        sizeEnd: 0.2,
        life: 0.55,
        lifeJitter: 0.3,
        burst: 26,
        rotRate: 1.8,
        color0: FIRE_HOT,
        color1: FIRE_MID,
        color2: FIRE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 0,
        dirY: 2.6,
        spread: 1.15,
        gravity: 4.2,
        drag: 0.12,
        noise: 0.5,
        size: 0.16,
        sizeEnd: 0.03,
        life: 0.72,
        lifeJitter: 0.45,
        burst: 22,
        color0: EMBER_HOT,
        color1: EMBER_MID,
        color2: EMBER_DEEP,
        lod: LodRank.Trail,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 0,
        dirY: 1.1,
        spread: 0.7,
        gravity: -0.85,
        drag: 1.5,
        noise: 0.5,
        size: 0.6,
        sizeEnd: 2.6,
        life: 1.9,
        lifeJitter: 0.4,
        opacity: 0.12,
        burst: 8,
        rotRate: 0.35,
        color0: SMOKE_HOT,
        color1: SMOKE_MID,
        color2: SMOKE_DEEP,
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AdditiveFire,
        atlasUv: ATLAS_UV.fire,
        rate: 30,
        dirY: 2.0,
        spread: 0.45,
        gravity: -1.1,
        drag: 0.9,
        noise: 0.6,
        size: 0.5,
        sizeEnd: 0.12,
        life: 0.7,
        lifeJitter: 0.4,
        rotRate: 1.2,
        color0: FIRE_HOT,
        color1: FIRE_MID,
        color2: FIRE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 14,
        dirY: 2.8,
        spread: 0.5,
        gravity: 2.6,
        drag: 0.15,
        noise: 0.8,
        size: 0.1,
        sizeEnd: 0.02,
        life: 0.9,
        lifeJitter: 0.5,
        color0: EMBER_HOT,
        color1: EMBER_MID,
        color2: EMBER_DEEP,
        lod: LodRank.Trail,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 10,
        dirY: 0.9,
        spread: 0.6,
        gravity: -0.7,
        drag: 1.5,
        noise: 0.45,
        size: 0.55,
        sizeEnd: 2.2,
        life: 2.2,
        lifeJitter: 0.4,
        opacity: 0.09,
        rotRate: 0.3,
        color0: SMOKE_HOT,
        color1: SMOKE_MID,
        color2: SMOKE_DEEP,
        lod: LodRank.Trail,
      },
    ],
  },

  frost: {
    cast: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.ice,
        rate: 34,
        dirY: 0.5,
        spread: 0.55,
        gravity: 0.5,
        drag: 0.5,
        noise: 0.4,
        size: 0.22,
        sizeEnd: 0.05,
        life: 0.6,
        lifeJitter: 0.35,
        burst: 7,
        rotRate: 1.6,
        color0: ICE_HOT,
        color1: ICE_MID,
        color2: ICE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 18,
        dirY: 0.8,
        spread: 0.5,
        gravity: 0.2,
        drag: 0.4,
        size: 0.16,
        sizeEnd: 0.03,
        life: 0.42,
        lifeJitter: 0.3,
        burst: 4,
        rotRate: 0,
        rotJitter: 0.3,
        color0: ICE_HOT,
        color1: "#e0f2fe",
        color2: "#7dd3fc",
        lod: LodRank.Trail,
      },
    ],
    trail: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.ice,
        rate: 30,
        dirY: 0.2,
        spread: 0.35,
        gravity: 0.6,
        drag: 0.6,
        noise: 0.35,
        size: 0.2,
        sizeEnd: 0.04,
        life: 0.7,
        lifeJitter: 0.4,
        rotRate: 1.8,
        color0: ICE_HOT,
        color1: ICE_MID,
        color2: ICE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 18,
        dirY: 0.12,
        spread: 0.5,
        gravity: 0.35,
        drag: 1.7,
        noise: 0.4,
        size: 0.42,
        sizeEnd: 1.5,
        life: 1.3,
        lifeJitter: 0.4,
        opacity: 0.05,
        rotRate: 0.2,
        color0: FROST_FOG_HOT,
        color1: FROST_FOG_MID,
        color2: FROST_FOG_DEEP,
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.ice,
        rate: 0,
        dirY: 1.6,
        spread: 1.1,
        gravity: 2.2,
        drag: 0.3,
        noise: 0.45,
        size: 0.32,
        sizeEnd: 0.06,
        life: 0.95,
        lifeJitter: 0.45,
        burst: 24,
        rotRate: 2.4,
        color0: ICE_HOT,
        color1: ICE_MID,
        color2: ICE_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 0,
        dirY: 1.9,
        spread: 1.0,
        gravity: 1.4,
        drag: 0.25,
        size: 0.2,
        sizeEnd: 0.03,
        life: 0.5,
        lifeJitter: 0.35,
        burst: 16,
        rotRate: 0,
        rotJitter: 0.3,
        color0: ICE_HOT,
        color1: "#e0f2fe",
        color2: "#7dd3fc",
        lod: LodRank.Trail,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 0,
        dirY: 0.3,
        spread: 0.95,
        gravity: 0.5,
        drag: 1.9,
        noise: 0.4,
        size: 0.6,
        sizeEnd: 2.4,
        life: 1.8,
        lifeJitter: 0.4,
        opacity: 0.07,
        burst: 10,
        rotRate: 0.2,
        color0: FROST_FOG_HOT,
        color1: FROST_FOG_MID,
        color2: FROST_FOG_DEEP,
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        /** Frost fog does not rise — it pours down and spreads (sandbox height-field read). */
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 22,
        dirY: 0.1,
        spread: 0.85,
        gravity: 0.28,
        drag: 1.9,
        noise: 0.4,
        size: 0.7,
        sizeEnd: 2.6,
        life: 2.6,
        lifeJitter: 0.45,
        opacity: 0.06,
        rotRate: 0.18,
        color0: FROST_FOG_HOT,
        color1: FROST_FOG_MID,
        color2: FROST_FOG_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.ice,
        rate: 12,
        dirY: 0.55,
        spread: 0.7,
        gravity: 0.75,
        drag: 0.55,
        noise: 0.5,
        size: 0.16,
        sizeEnd: 0.04,
        life: 1.5,
        lifeJitter: 0.5,
        rotRate: 1.3,
        color0: ICE_HOT,
        color1: ICE_MID,
        color2: ICE_DEEP,
        lod: LodRank.Trail,
      },
    ],
  },

  poison: {
    cast: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 42,
        dirY: 1.0,
        spread: 0.5,
        gravity: -0.2,
        drag: 0.6,
        noise: 0.75,
        size: 0.22,
        sizeEnd: 0.05,
        life: 0.5,
        lifeJitter: 0.3,
        burst: 8,
        color0: TOX_HOT,
        color1: TOX_MID,
        color2: TOX_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 14,
        dirY: 0.5,
        spread: 0.55,
        gravity: -0.15,
        drag: 1.3,
        noise: 0.5,
        size: 0.4,
        sizeEnd: 1.3,
        life: 1.3,
        lifeJitter: 0.35,
        opacity: 0.1,
        rotRate: 0.3,
        color0: TOX_FOG_HOT,
        color1: TOX_FOG_MID,
        color2: TOX_FOG_DEEP,
        lod: LodRank.Trail,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 30,
        dirY: 0.2,
        spread: 0.4,
        gravity: 0.4,
        drag: 0.5,
        noise: 0.8,
        size: 0.17,
        sizeEnd: 0.035,
        life: 0.48,
        lifeJitter: 0.35,
        color0: TOX_HOT,
        color1: TOX_MID,
        color2: TOX_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 12,
        dirY: 0.25,
        spread: 0.45,
        gravity: -0.05,
        drag: 1.5,
        noise: 0.45,
        size: 0.35,
        sizeEnd: 1.2,
        life: 1.2,
        opacity: 0.07,
        rotRate: 0.25,
        color0: TOX_FOG_HOT,
        color1: TOX_FOG_MID,
        color2: TOX_FOG_DEEP,
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 0,
        dirY: 1.7,
        spread: 1.2,
        gravity: 1.9,
        drag: 0.35,
        noise: 0.8,
        size: 0.26,
        sizeEnd: 0.05,
        life: 0.75,
        lifeJitter: 0.4,
        burst: 22,
        color0: TOX_HOT,
        color1: TOX_MID,
        color2: TOX_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 0,
        dirY: 0.7,
        spread: 0.9,
        gravity: -0.2,
        drag: 1.6,
        noise: 0.5,
        size: 0.55,
        sizeEnd: 2.1,
        life: 1.7,
        lifeJitter: 0.4,
        opacity: 0.11,
        burst: 10,
        rotRate: 0.3,
        color0: TOX_FOG_HOT,
        color1: TOX_FOG_MID,
        color2: TOX_FOG_DEEP,
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 24,
        dirY: 0.45,
        spread: 0.8,
        gravity: -0.22,
        drag: 1.5,
        noise: 0.5,
        size: 0.75,
        sizeEnd: 2.4,
        life: 2.6,
        lifeJitter: 0.45,
        opacity: 0.1,
        rotRate: 0.25,
        color0: TOX_FOG_HOT,
        color1: TOX_FOG_MID,
        color2: TOX_FOG_DEEP,
        lod: LodRank.Core,
      },
      {
        /** Bubbles welling up out of the sludge — slow, wobbly, pop high. */
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 13,
        dirY: 1.1,
        spread: 0.45,
        gravity: -0.35,
        drag: 0.85,
        noise: 0.85,
        size: 0.2,
        sizeEnd: 0.05,
        life: 1.5,
        lifeJitter: 0.5,
        color0: TOX_HOT,
        color1: TOX_MID,
        color2: TOX_DEEP,
        lod: LodRank.Trail,
      },
    ],
  },

  lightning: {
    cast: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 30,
        dirY: 0.5,
        spread: 0.7,
        gravity: 0.3,
        drag: 0.5,
        noise: 1.3,
        size: 0.16,
        sizeEnd: 0.025,
        life: 0.26,
        lifeJitter: 0.4,
        burst: 8,
        rotRate: 0,
        rotJitter: 0.25,
        color0: ARC_HOT,
        color1: ARC_MID,
        color2: ARC_DEEP,
        lod: LodRank.Core,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 22,
        dirY: 0.2,
        spread: 0.6,
        gravity: 0.8,
        drag: 0.4,
        noise: 1.4,
        size: 0.13,
        sizeEnd: 0.02,
        life: 0.24,
        lifeJitter: 0.45,
        rotRate: 0,
        rotJitter: 0.25,
        color0: ARC_HOT,
        color1: ARC_MID,
        color2: ARC_DEEP,
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 0,
        dirY: 2.4,
        spread: 1.3,
        gravity: 3.0,
        drag: 0.2,
        noise: 1.2,
        size: 0.2,
        sizeEnd: 0.03,
        life: 0.4,
        lifeJitter: 0.5,
        burst: 24,
        rotRate: 0,
        rotJitter: 0.25,
        color0: ARC_HOT,
        color1: ARC_MID,
        color2: ARC_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 0,
        dirY: 0.8,
        spread: 0.8,
        gravity: -0.5,
        drag: 1.6,
        noise: 0.4,
        size: 0.5,
        sizeEnd: 2.0,
        life: 1.6,
        opacity: 0.07,
        burst: 7,
        rotRate: 0.3,
        color0: "#3d546e",
        color1: "#33475e",
        color2: "#1c2938",
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 16,
        dirY: 1.6,
        spread: 0.8,
        gravity: 2.2,
        drag: 0.3,
        noise: 1.3,
        size: 0.14,
        sizeEnd: 0.02,
        life: 0.5,
        lifeJitter: 0.5,
        rotRate: 0,
        rotJitter: 0.25,
        color0: ARC_HOT,
        color1: ARC_MID,
        color2: ARC_DEEP,
        lod: LodRank.Trail,
      },
    ],
  },

  void: {
    cast: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.void,
        rate: 34,
        dirY: 0.7,
        spread: 0.55,
        gravity: -0.2,
        drag: 0.7,
        noise: 0.6,
        size: 0.4,
        sizeEnd: 0.08,
        life: 0.48,
        lifeJitter: 0.3,
        burst: 8,
        rotRate: 1.5,
        color0: VOID_HOT,
        color1: VOID_MID,
        color2: VOID_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.void,
        rate: 16,
        dirY: 0.4,
        spread: 0.5,
        gravity: -0.1,
        drag: 1.1,
        noise: 0.4,
        size: 0.5,
        sizeEnd: 1.1,
        life: 0.95,
        opacity: 0.5,
        rotRate: 0.9,
        color0: VOID_MASS_HOT,
        color1: VOID_MASS_MID,
        color2: VOID_MASS_DEEP,
        lod: LodRank.Trail,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.void,
        rate: 28,
        dirY: 0.15,
        spread: 0.4,
        gravity: -0.05,
        drag: 0.8,
        noise: 0.7,
        size: 0.34,
        sizeEnd: 0.06,
        life: 0.42,
        lifeJitter: 0.35,
        rotRate: 1.7,
        color0: VOID_HOT,
        color1: VOID_MID,
        color2: VOID_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 14,
        dirY: 0.3,
        spread: 0.7,
        gravity: 0.1,
        size: 0.14,
        sizeEnd: 0.02,
        life: 0.35,
        color0: "#fae8ff",
        color1: "#e879f9",
        color2: "#86198f",
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        /** Void lands as an implosion: particles thrown out, then dragged back to a point. */
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.void,
        rate: 0,
        dirY: 1.2,
        spread: 1.35,
        gravity: -0.3,
        drag: 1.6,
        noise: 0.7,
        size: 0.5,
        sizeEnd: 0.08,
        life: 0.7,
        lifeJitter: 0.4,
        burst: 24,
        rotRate: 2.0,
        color0: VOID_HOT,
        color1: VOID_MID,
        color2: VOID_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.void,
        rate: 0,
        dirY: 0.5,
        spread: 1.0,
        gravity: -0.15,
        drag: 1.4,
        noise: 0.45,
        size: 0.75,
        sizeEnd: 1.9,
        life: 1.3,
        opacity: 0.45,
        burst: 10,
        rotRate: 1.0,
        color0: VOID_MASS_HOT,
        color1: VOID_MASS_MID,
        color2: VOID_MASS_DEEP,
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.void,
        rate: 18,
        dirY: 0.55,
        spread: 0.8,
        gravity: -0.28,
        drag: 1.3,
        noise: 0.45,
        size: 0.7,
        sizeEnd: 2.0,
        life: 2.2,
        lifeJitter: 0.4,
        opacity: 0.4,
        rotRate: 0.7,
        color0: VOID_MASS_HOT,
        color1: VOID_MASS_MID,
        color2: VOID_MASS_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 10,
        dirY: 1.3,
        spread: 0.7,
        gravity: -0.15,
        drag: 0.6,
        size: 0.16,
        sizeEnd: 0.02,
        life: 0.9,
        lifeJitter: 0.5,
        color0: "#fae8ff",
        color1: "#e879f9",
        color2: "#86198f",
        lod: LodRank.Trail,
      },
    ],
  },

  wind: {
    cast: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.wind,
        rate: 38,
        dirZ: 1.6,
        dirY: 0.4,
        spread: 0.45,
        gravity: 0.02,
        drag: 0.5,
        noise: 0.5,
        size: 0.6,
        sizeEnd: 0.2,
        life: 0.4,
        lifeJitter: 0.3,
        burst: 7,
        rotRate: 0,
        rotJitter: 0,
        color0: WIND_HOT,
        color1: WIND_MID,
        color2: WIND_DEEP,
        lod: LodRank.Core,
      },
    ],
    trail: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.wind,
        rate: 30,
        dirZ: 1.2,
        dirY: 0.25,
        spread: 0.4,
        gravity: 0.02,
        drag: 0.6,
        noise: 0.55,
        size: 0.55,
        sizeEnd: 0.15,
        life: 0.35,
        lifeJitter: 0.35,
        rotRate: 0,
        rotJitter: 0,
        color0: WIND_HOT,
        color1: WIND_MID,
        color2: WIND_DEEP,
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.wind,
        rate: 0,
        dirY: 0.7,
        spread: 1.4,
        gravity: 0.05,
        drag: 0.75,
        noise: 0.6,
        size: 1.0,
        sizeEnd: 0.3,
        life: 0.5,
        lifeJitter: 0.35,
        burst: 26,
        rotRate: 0,
        rotJitter: 0,
        color0: WIND_HOT,
        color1: WIND_MID,
        color2: WIND_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 0,
        dirY: 0.35,
        spread: 1.1,
        gravity: -0.1,
        drag: 1.5,
        noise: 0.5,
        size: 0.5,
        sizeEnd: 2.0,
        life: 1.2,
        opacity: 0.07,
        burst: 8,
        rotRate: 0.25,
        color0: WIND_HOT,
        color1: WIND_MID,
        color2: "#cbd5e1",
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AlphaIce,
        atlasUv: ATLAS_UV.wind,
        rate: 20,
        dirZ: 1.4,
        dirY: 0.3,
        spread: 0.5,
        gravity: 0.02,
        drag: 0.55,
        noise: 0.6,
        size: 0.7,
        sizeEnd: 0.22,
        life: 0.7,
        lifeJitter: 0.4,
        rotRate: 0,
        rotJitter: 0,
        color0: WIND_HOT,
        color1: WIND_MID,
        color2: WIND_DEEP,
        lod: LodRank.Trail,
      },
    ],
  },

  heal: {
    cast: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.leaf,
        rate: 24,
        dirY: 0.9,
        spread: 0.45,
        gravity: -0.15,
        drag: 0.55,
        noise: 0.4,
        size: 0.26,
        sizeEnd: 0.07,
        life: 0.9,
        lifeJitter: 0.35,
        burst: 6,
        rotRate: 1.3,
        rotJitter: 1,
        color0: LEAF_HOT,
        color1: LEAF_MID,
        color2: LEAF_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 14,
        dirY: 1.2,
        spread: 0.5,
        gravity: 0.1,
        drag: 0.5,
        size: 0.15,
        sizeEnd: 0.03,
        life: 0.5,
        rotRate: 0,
        rotJitter: 0.3,
        color0: "#fffbeb",
        color1: "#fef08a",
        color2: LEAF_MID,
        lod: LodRank.Trail,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.leaf,
        rate: 22,
        dirY: 0.3,
        spread: 0.35,
        gravity: 0.1,
        drag: 0.5,
        noise: 0.4,
        size: 0.24,
        sizeEnd: 0.06,
        life: 0.8,
        lifeJitter: 0.4,
        rotRate: 1.6,
        rotJitter: 1,
        color0: LEAF_HOT,
        color1: LEAF_MID,
        color2: LEAF_DEEP,
        lod: LodRank.Core,
      },
    ],
    impact: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.leaf,
        rate: 0,
        dirY: 1.5,
        spread: 1.2,
        gravity: -0.25,
        drag: 0.9,
        noise: 0.45,
        size: 0.34,
        sizeEnd: 0.07,
        life: 1.2,
        lifeJitter: 0.4,
        burst: 22,
        rotRate: 1.5,
        rotJitter: 1,
        color0: LEAF_HOT,
        color1: LEAF_MID,
        color2: LEAF_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 0,
        dirY: 2.0,
        spread: 1.0,
        gravity: -0.1,
        drag: 0.8,
        size: 0.18,
        sizeEnd: 0.03,
        life: 0.6,
        lifeJitter: 0.35,
        burst: 14,
        rotRate: 0,
        rotJitter: 0.3,
        color0: "#fffbeb",
        color1: "#fef08a",
        color2: LEAF_MID,
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.leaf,
        rate: 16,
        dirY: 1.0,
        spread: 0.7,
        gravity: -0.3,
        drag: 0.7,
        noise: 0.45,
        size: 0.26,
        sizeEnd: 0.06,
        life: 1.6,
        lifeJitter: 0.5,
        rotRate: 1.2,
        rotJitter: 1,
        color0: LEAF_HOT,
        color1: LEAF_MID,
        color2: LEAF_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 10,
        dirY: 0.4,
        spread: 0.7,
        gravity: -0.35,
        drag: 1.5,
        noise: 0.4,
        size: 0.5,
        sizeEnd: 1.9,
        life: 2.0,
        opacity: 0.045,
        rotRate: 0.2,
        color0: "#dcfce7",
        color1: LEAF_MID,
        color2: "#14532d",
        lod: LodRank.Trail,
      },
    ],
  },

  holy: {
    cast: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 34,
        dirY: 1.3,
        spread: 0.4,
        gravity: 0.1,
        drag: 0.5,
        noise: 0.3,
        size: 0.28,
        sizeEnd: 0.05,
        life: 0.55,
        lifeJitter: 0.3,
        burst: 8,
        rotRate: 0,
        rotJitter: 0.3,
        color0: HOLY_HOT,
        color1: HOLY_MID,
        color2: HOLY_DEEP,
        lod: LodRank.Core,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 24,
        dirY: 0.6,
        spread: 0.45,
        gravity: 0.15,
        drag: 0.55,
        size: 0.22,
        sizeEnd: 0.04,
        life: 0.5,
        lifeJitter: 0.35,
        rotRate: 0,
        rotJitter: 0.3,
        color0: HOLY_HOT,
        color1: HOLY_MID,
        color2: HOLY_DEEP,
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 0,
        dirY: 2.4,
        spread: 1.1,
        gravity: 0.2,
        drag: 0.7,
        noise: 0.35,
        size: 0.42,
        sizeEnd: 0.06,
        life: 0.8,
        lifeJitter: 0.4,
        burst: 26,
        rotRate: 0,
        rotJitter: 0.3,
        color0: HOLY_HOT,
        color1: HOLY_MID,
        color2: HOLY_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 0,
        dirY: 1.6,
        spread: 1.25,
        gravity: 0.9,
        drag: 0.4,
        size: 0.2,
        sizeEnd: 0.03,
        life: 0.6,
        lifeJitter: 0.4,
        burst: 16,
        color0: "#fefce8",
        color1: "#fde68a",
        color2: "#ca8a04",
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.glint,
        rate: 18,
        dirY: 1.5,
        spread: 0.65,
        gravity: 0.05,
        drag: 0.6,
        noise: 0.35,
        size: 0.26,
        sizeEnd: 0.04,
        life: 1.3,
        lifeJitter: 0.5,
        rotRate: 0,
        rotJitter: 0.3,
        color0: HOLY_HOT,
        color1: HOLY_MID,
        color2: HOLY_DEEP,
        lod: LodRank.Core,
      },
    ],
  },

  blood: {
    cast: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 36,
        dirY: 0.2,
        spread: 0.72,
        gravity: 0.55,
        drag: 0.55,
        noise: 0.45,
        size: 0.14,
        sizeEnd: 0.03,
        life: 0.38,
        lifeJitter: 0.2,
        opacity: 0.88,
        burst: 10,
        rotRate: 0.35,
        rotJitter: 0.4,
        color0: BLOOD_HOT,
        color1: BLOOD_MID,
        color2: BLOOD_DEEP,
        lod: LodRank.Core,
      },
    ],
    trail: [
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 28,
        dirY: -0.15,
        spread: 0.3,
        gravity: 1.9,
        drag: 0.12,
        noise: 0.25,
        size: 0.11,
        sizeEnd: 0.025,
        life: 0.5,
        lifeJitter: 0.35,
        opacity: 0.85,
        rotRate: 0.2,
        rotJitter: 0.4,
        color0: "#f87171",
        color1: "#b91c1c",
        color2: "#450a0a",
        lod: LodRank.Trail,
      },
    ],
    impact: [
      {
        /** Spill, not spray — heavy gravity, low noise, reads as fluid. */
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 0,
        dirY: -1.0,
        spread: 0.9,
        gravity: 6.0,
        drag: 0.05,
        noise: 0.12,
        size: 0.2,
        sizeEnd: 0.05,
        life: 0.85,
        lifeJitter: 0.25,
        opacity: 0.95,
        burst: 24,
        rotRate: 0.15,
        rotJitter: 0.4,
        color0: BLOOD_HOT,
        color1: BLOOD_MID,
        color2: BLOOD_DEEP,
        lod: LodRank.Core,
      },
      {
        batch: BatchId.AdditiveSpark,
        atlasUv: ATLAS_UV.spark,
        rate: 0,
        dirY: 0.6,
        spread: 1.35,
        gravity: 4.0,
        drag: 0.1,
        noise: 0.3,
        size: 0.12,
        sizeEnd: 0.025,
        life: 0.6,
        lifeJitter: 0.4,
        opacity: 0.8,
        burst: 16,
        rotRate: 0.1,
        rotJitter: 0.4,
        color0: "#f87171",
        color1: "#b91c1c",
        color2: "#450a0a",
        lod: LodRank.Trail,
      },
    ],
    ground: [
      {
        batch: BatchId.AlphaSmoke,
        atlasUv: ATLAS_UV.smoke,
        rate: 12,
        dirY: 0.2,
        spread: 0.75,
        gravity: -0.15,
        drag: 1.2,
        noise: 0.35,
        size: 0.5,
        sizeEnd: 1.7,
        life: 1.6,
        lifeJitter: 0.4,
        opacity: 0.1,
        rotRate: 0.2,
        color0: "#9f1239",
        color1: "#4c0519",
        color2: "#1c0508",
        lod: LodRank.Trail,
      },
    ],
  },
};

/** Raw recipe access — for effects that need to tweak a single layer before spawning. */
export function elementRoleLayers(
  element: ElementId,
  role: ElementRole,
): readonly Layer[] {
  return PRESETS[element][role];
}

/**
 * Live handle over one element role's emitters.
 *
 * Methods are bound to preallocated arrays, so driving these every frame costs no
 * allocations. `setRateScale` multiplies each layer's authored rate, which keeps the
 * mix between core/sparks/mist intact while a spell fades in or out.
 */
export type ElementHandle = {
  readonly ids: readonly number[];
  /** Move all layers; authored per-layer direction is preserved. */
  setPose(x: number, y: number, z: number): void;
  /** Move all layers and rotate authored directions so +Z means `yaw` forward. */
  setPoseYaw(x: number, y: number, z: number, yaw: number): void;
  /** Multiply every layer's authored rate (0 silences, 1 restores). */
  setRateScale(scale: number): void;
  kill(): void;
};

const NOOP_HANDLE: ElementHandle = {
  ids: [],
  setPose: () => {},
  setPoseYaw: () => {},
  setRateScale: () => {},
  kill: () => {},
};

/**
 * Spawn one element role at a world point.
 *
 * `overrides` is applied to every layer, so it is the right place for things that are
 * true of the whole effect (`duration`, a global `rate` gate, a color retint) and the
 * wrong place for per-layer tuning — use `elementRoleLayers` and `spawnEmitter` for that.
 */
export function spawnElementRole(
  element: ElementId,
  role: ElementRole,
  x: number,
  y: number,
  z: number,
  overrides?: Partial<EmitterSpawn>,
): ElementHandle {
  const layers = PRESETS[element][role];
  const ids: number[] = [];
  const baseRates: number[] = [];
  const dirX: number[] = [];
  const dirY: number[] = [];
  const dirZ: number[] = [];

  for (const layer of layers) {
    const cfg: EmitterSpawn = { ...BASE, ...layer, ...overrides, x, y, z };
    const id = spawnEmitter(cfg);
    if (id < 0) continue;
    ids.push(id);
    baseRates.push(cfg.rate ?? 0);
    dirX.push(cfg.dirX ?? 0);
    dirY.push(cfg.dirY ?? 0);
    dirZ.push(cfg.dirZ ?? 0);
  }
  if (ids.length === 0) return NOOP_HANDLE;

  return {
    ids,
    setPose(px, py, pz) {
      for (let i = 0; i < ids.length; i++) {
        setEmitterPose(ids[i]!, px, py, pz, dirX[i], dirY[i], dirZ[i]);
      }
    },
    setPoseYaw(px, py, pz, yaw) {
      const s = Math.sin(yaw);
      const c = Math.cos(yaw);
      for (let i = 0; i < ids.length; i++) {
        const dx = dirX[i]!;
        const dz = dirZ[i]!;
        setEmitterPose(ids[i]!, px, py, pz, dx * c + dz * s, dirY[i], -dx * s + dz * c);
      }
    },
    setRateScale(scale) {
      for (let i = 0; i < ids.length; i++) {
        setEmitterRate(ids[i]!, baseRates[i]! * scale);
      }
    },
    kill() {
      for (const id of ids) killEmitter(id);
      ids.length = 0;
    },
  };
}

/** One-shot burst: spawns the role, lets its burst fire, then self-expires. */
export function burstElementRole(
  element: ElementId,
  role: ElementRole,
  x: number,
  y: number,
  z: number,
  overrides?: Partial<EmitterSpawn>,
): void {
  spawnElementRole(element, role, x, y, z, { duration: 0.05, ...overrides });
}
