/** Curated game-icons.net assets under public/icons/game (white SVGs). */

export const GAME_ICON_IDS = [
  "animal-hide",
  "archery-target",
  "armor-cuisses",
  "aura",
  "belt",
  "belt-armor",
  "blood",
  "blue-gem",
  "bolt-spell-cast",
  "boot-kick",
  "boots",
  "breastplate",
  "brick-wall",
  "burning-meteor",
  "cape",
  "chest-armor",
  "cloak",
  "cloak-dagger",
  "cluster-bomb",
  "cog",
  "crosshair",
  "crossed-chains",
  "crossed-swords",
  "door",
  "drama-masks",
  "drop",
  "exit-door",
  "explosion-rays",
  "fire-spell-cast",
  "fireball",
  "fish-scales",
  "fist",
  "flame",
  "frozen-orb",
  "gauntlet",
  "gloves",
  "healing",
  "health-potion",
  "heart-plus",
  "help",
  "hidden",
  "hourglass",
  "ice-bolt",
  "ink-swirl",
  "invisible",
  "knockout",
  "leather-boot",
  "lightning-trio",
  "locked-chest",
  "magic-hat",
  "magic-portal",
  "magic-swirl",
  "mailed-fist",
  "metal-scales",
  "move",
  "musical-notes",
  "mute",
  "paint-brush",
  "palette",
  "party-flags",
  "pointy-hat",
  "poison-bottle",
  "portal",
  "power-lightning",
  "punch",
  "radar-sweep",
  "red-gem",
  "return-arrow",
  "robe",
  "scroll-unfurled",
  "shield",
  "shield-reflect",
  "shiny-purse",
  "shoulder-armor",
  "silence",
  "skills",
  "sparkles",
  "spell-book",
  "sprint",
  "standing-potion",
  "star-struck",
  "stone-wall",
  "stopwatch",
  "sword-brandish",
  "switch-weapon",
  "talk",
  "three-friends",
  "tree-roots",
  "trousers",
  "two-coins",
  "vortex",
  "water-drop",
  "whirlwind",
  "wingfoot",
  "wizard-staff",
] as const;

export type GameIconId = (typeof GAME_ICON_IDS)[number];

/** Authors for attribution (game-icons.net / CC BY 3.0 unless noted). */
export const GAME_ICON_AUTHORS: Record<GameIconId, string> = {
  "animal-hide": "Delapouite",
  "archery-target": "Lorc",
  "armor-cuisses": "Delapouite",
  aura: "Lorc",
  belt: "Lucas",
  "belt-armor": "Delapouite",
  blood: "Skoll",
  "blue-gem": "Lorc",
  "bolt-spell-cast": "Delapouite",
  "boot-kick": "Lorc",
  boots: "Lorc",
  breastplate: "Lorc",
  "brick-wall": "Delapouite",
  "burning-meteor": "Lorc",
  cape: "Delapouite",
  "chest-armor": "Delapouite",
  cloak: "Lucas",
  "cloak-dagger": "Lorc",
  "cluster-bomb": "Lorc",
  cog: "Lorc",
  crosshair: "Delapouite",
  "crossed-chains": "Lorc",
  "crossed-swords": "Lorc",
  door: "Delapouite",
  "drama-masks": "Lorc",
  drop: "Lorc",
  "exit-door": "Delapouite",
  "explosion-rays": "Lorc",
  "fire-spell-cast": "Delapouite",
  fireball: "Lorc",
  "fish-scales": "Delapouite",
  fist: "Lorc",
  flame: "Carl Olsen",
  "frozen-orb": "Lorc",
  gauntlet: "Delapouite",
  gloves: "Delapouite",
  healing: "Delapouite",
  "health-potion": "Delapouite",
  "heart-plus": "Zeromancer",
  help: "sbed",
  hidden: "Lorc",
  hourglass: "Lorc",
  "ice-bolt": "Lorc",
  "ink-swirl": "Lorc",
  invisible: "Delapouite",
  knockout: "Skoll",
  "leather-boot": "Lorc",
  "lightning-trio": "Lorc",
  "locked-chest": "Lorc",
  "magic-hat": "Delapouite",
  "magic-portal": "Lorc",
  "magic-swirl": "Lorc",
  "mailed-fist": "Lorc",
  "metal-scales": "Lorc",
  move: "Delapouite",
  "musical-notes": "Delapouite",
  mute: "Delapouite",
  "paint-brush": "Delapouite",
  palette: "Delapouite",
  "party-flags": "Delapouite",
  "pointy-hat": "Lorc",
  "poison-bottle": "Lorc",
  portal: "Lorc",
  "power-lightning": "Lorc",
  punch: "Lorc",
  "radar-sweep": "Lorc",
  "red-gem": "Lorc",
  "return-arrow": "Lorc",
  robe: "Lorc",
  "scroll-unfurled": "Lorc",
  shield: "sbed",
  "shield-reflect": "Lorc",
  "shiny-purse": "Lorc",
  "shoulder-armor": "Delapouite",
  silence: "Lorc",
  skills: "Delapouite",
  sparkles: "Delapouite",
  "spell-book": "Delapouite",
  sprint: "Lorc",
  "standing-potion": "Lorc",
  "star-struck": "Delapouite",
  "stone-wall": "Delapouite",
  stopwatch: "Skoll",
  "sword-brandish": "Delapouite",
  "switch-weapon": "Delapouite",
  talk: "Skoll",
  "three-friends": "Delapouite",
  "tree-roots": "Delapouite",
  trousers: "Lorc",
  "two-coins": "Delapouite",
  vortex: "Lorc",
  "water-drop": "sbed",
  whirlwind: "Lorc",
  wingfoot: "Lorc",
  "wizard-staff": "Lorc",
};

export type CosmeticSlotIcon =
  | "hat"
  | "shoulders"
  | "chest"
  | "gloves"
  | "belt"
  | "legs"
  | "shoes";

export const GEAR_SLOT_ICONS: Record<CosmeticSlotIcon, GameIconId> = {
  hat: "pointy-hat",
  shoulders: "shoulder-armor",
  chest: "chest-armor",
  gloves: "gauntlet",
  belt: "belt-armor",
  legs: "armor-cuisses",
  shoes: "boots",
};

export const SHOP_CATEGORY_ICONS: Record<
  "cosmetics" | "emotes" | "loadouts" | "consumables",
  GameIconId
> = {
  cosmetics: "sparkles",
  emotes: "drama-masks",
  loadouts: "skills",
  consumables: "health-potion",
};

export const COSMETIC_GROUP_ICONS: Record<"tints" | "inks" | "patterns" | "gear", GameIconId> = {
  tints: "animal-hide",
  inks: "ink-swirl",
  patterns: "fish-scales",
  gear: "chest-armor",
};

/** Talent tree rail tabs. */
export const TALENT_TREE_ICONS: Record<
  "Destruction" | "Guardian" | "Flow" | "Harmony" | "Control",
  GameIconId
> = {
  Destruction: "fireball",
  Guardian: "shield",
  Flow: "wingfoot",
  Harmony: "heart-plus",
  Control: "crossed-chains",
};
